---
- hosts: cisco
  connection: local
  gather_facts: False
  tasks:
    - name: run show version
      nxos_facts:
        provider: "{{login_info}}"
      register: all_facts

#    - debug:
#        var: all_facts

    - template:
        src: report.j2
        dest: ./generated_report.html
      delegate_to: localhost
      run_once: true
      with_items:
